[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_global_article = "HDcgnQy7KCYyRoHccLQCHk5tWZAvaoNFowHjRhXC9G74"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ed/.config/solana/wallet/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
